use enterpriseservices;


declare @user varchar(8) = '<username>';
declare @program varchar(8) = 'SSMS';

SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction';


select *
from  APPL_PROPERTY_VALU
where APPL_ID in
(
SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction'
)
order by APPL_PRPTY_NM, APPL_PRPTY_VALUE;

insert into APPL_REFRESH (APPL_ID, REFRSH_PRPTY_FLG, REFRSH_PRPTY_FREQ, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'Y',
	'42000',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY_VALU (APPL_ID, APPL_PRPTY_NM, APPL_PRPTY_VALUE, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'ENABLE_NOTIFICATIONS',
	'OFF',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY_VALU (APPL_ID, APPL_PRPTY_NM, APPL_PRPTY_VALUE, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'LOG_INCOMING_XML',
	'ON',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY_VALU (APPL_ID, APPL_PRPTY_NM, APPL_PRPTY_VALUE, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'VALIDATE_INCOMING_XML',
	'OFF',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY_VALU (APPL_ID, APPL_PRPTY_NM, APPL_PRPTY_VALUE, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'ORDER_SERVICES_CONNECT_TIMEOUT',
	'5000',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY_VALU (APPL_ID, APPL_PRPTY_NM, APPL_PRPTY_VALUE, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'ORDER_SERVICES_READ_TIMEOUT',
	'5000',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY_VALU (APPL_ID, APPL_PRPTY_NM, APPL_PRPTY_VALUE, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'APPLICATION_PORTAL_CONNECT_TIMEOUT',
	'5000',
	@program,
	@user,
	CURRENT_TIMESTAMP
);
 
insert into APPL_PROPERTY_VALU (APPL_ID, APPL_PRPTY_NM, APPL_PRPTY_VALUE, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'APPLICATION_PORTAL_READ_TIMEOUT',
	'5000',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY (APPL_ID, APPL_PRPTY_NM, SEQ_NBR, APPL_PRPTY_DESC, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'ENABLE_NOTIFICATIONS',
	'1', 
	'Flag to indicate if error notifications are enabled',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY (APPL_ID, APPL_PRPTY_NM, SEQ_NBR, APPL_PRPTY_DESC, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'LOG_INCOMING_XML',
	'2', 
	'Log incoming XML requests',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY (APPL_ID, APPL_PRPTY_NM, SEQ_NBR, APPL_PRPTY_DESC, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'VALIDATE_INCOMING_XML',
	'3', 
	'Validate incoming XML requests',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY (APPL_ID, APPL_PRPTY_NM, SEQ_NBR, APPL_PRPTY_DESC, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'ORDER_SERVICES_CONNECT_TIMEOUT',
	'4', 
	'Order services connection timeout',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY (APPL_ID, APPL_PRPTY_NM, SEQ_NBR, APPL_PRPTY_DESC, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'ORDER_SERVICES_READ_TIMEOUT',
	'5', 
	'Order services read timeout',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY (APPL_ID, APPL_PRPTY_NM, SEQ_NBR, APPL_PRPTY_DESC, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'APPLICATION_PORTAL_CONNECT_TIMEOUT',
	'6', 
	'Application portal connection timeout',
	@program,
	@user,
	CURRENT_TIMESTAMP
);

insert into APPL_PROPERTY (APPL_ID, APPL_PRPTY_NM, SEQ_NBR, APPL_PRPTY_DESC, AUD_PGM_ID, AUD_OPID, AUD_TS)
VALUES
(
	(SELECT APPL_ID FROM APPL_PWD WHERE APPL_SHRT_DESC = 'Customer Transaction') ,
	'APPLICATION_PORTAL_READ_TIMEOUT',
	'7', 
	'Application portal read timeout',
	@program,
	@user,
	CURRENT_TIMESTAMP
);
